name: Build AM32 F051 Firmware

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1

      - name: Install ARM SDK
        run: make arm_sdk_install

      - name: Get GitHub Build Number (ENV)
        id: get_buildno
        run: echo "GITHUBBUILDNUMBER=${{ github.run_number }}" >> $GITHUB_ENV
        continue-on-error: true

      - name: Get Pull Request Number
        id: get_pullno
        run: echo "PULL_NUMBER=$(echo "$GITHUB_REF" | awk -F / '{print $3}')" >> $GITHUB_ENV
        if: startsWith(github.ref, 'refs/pull/')

      - name: Make artifact name
        id: make_artifactname
        run: |
          ARTIFACT_NAME="AM32-BUILD-${{ github.run_number }}"
          echo "${ARTIFACT_NAME}"
          echo "ARTIFACT_NAME=${ARTIFACT_NAME}" >> $GITHUB_ENV

      - name: Build All Targets
        run: |
          make all
          wget https://gist.github.com/pavel-a/89d71b3aba9d7a9e6f8a61d728b08a8e/raw/7531987ba59997cddc3bd31fca8c69dd43fdafe2/bin2hexp.py
          python bin2hexp.py -A 0x08000000 -b PB4_BOOTLOADER_V11.bin -o obj/bootloader.hex
          python bin2hexp.py -A 0x08007c00 -b eeprom_version_1_7c00.bin -o obj/eeprom.hex
          echo obj/hsoon.hex
          echo AM32_HSOON_1.92.hex
          python -c "import IntelHex; original = IntelHex("obj/bootloader.hex"); new = IntelHex("obj/eeprom.hex"); original.merge(new, overlap='replace');new = IntelHex("obj/AM32_HSOON_1.92.hex"); original.merge(new, overlap='replace'); original.write_hex_file('obj/all.hex')"
          
      - name: Upload Bin Files
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}-BIN
          path: obj/*.bin
      
      - name: Upload Hex Files
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}-HEX
          path: obj/*.hex
